### PR TITLE
Make sidebar and diagnosis UI more responsive

### PR DESCRIPTION
**Pull request by jgoley**
@nathanathan This PR goes a little further with the responsiveness of the sidebar and diagnosis UI.
- decreases width of sidebar under 768px
- makes contents of sidebar responsive
- declutters button area in sidebar — uses icons (with tooltips)
- Styles tables for smaller screens - shows stuff in a more blocked layout (especially beneficial for the detailed diagnosis or symptom table) 
- Changes confidence value in sidebar table to a percentage with 2 decimal points
- updates bootstrap package

### CODE REVIEW

**Comment by nathanathan** [comment]
The changes looks good, but the feedback form isn't working for me. Also, while I was testing this I noticed some of the other recent changes are breaking the styling of the /searchEidr page.

**Comment by jgoley** [comment]
Oh no, my bad — I didn't venture too far away from the diagnosis detail page. I'll add some PT bugs and fix them ASAP.

**Comment by jgoley** [comment]
@nathanathan I've pushed a few commits that fix:
- search UI
- feedback modal
- disease/article table on the profile page (on small screens)

**Comment by nathanathan** [comment]
👍 Looks great!

**Pull request merged**
